### ISSUE TITLE
Uploading a contract to terra-2

### ISSUE THREAD

**Issue by daniel-wehbe** [andromedaprotocol/andromeda.js#78] opened 2023-07-19 15:43 UTC
Getting the following error when trying to upload a contract to terra testnet: Query failed with (6): rpc error: code = Unknown desc = account sequence mismatch, expected 30, got 29: incorrect account sequence [cosmos/cosmos-sdk@v0.46.11/x/auth/ante/sigverify.go:269] With gas wanted: '50000000' and gas used: '2346768' : unknown request
<img width="1036" alt="Screen Shot 2023-07-19 at 4 51 00 PM" src="https://github.com/andromedaprotocol/andromeda.js/assets/90905690/9afb05fa-4a43-42cb-b8a7-a059a092bf65">

Also creating a new wallet and requesting funds from faucet do not show in CLI. It gives the error, wallet does not exist, try sending some tokens but on explorer the wallet exists and has tokens . Not sure if both problems are related.

**Comment by leifasorensen** [comment] 2024-01-31 15:53
@daniel-wehbe 
I have opened an issue for the wallet to explorer conflict in Issue #95 . I believe this will be the source of that related conflict.

I would recommend retrying the `wasm upload` related issue to see if this is still occurring.

**Comment by leifasorensen** [comment] 2024-02-14 14:57
From what I can see this is a concurrency conflict with the wallet being used for signing having faults due to a sequence mismatch. Sequencing (as referred to in the error) is used to prevent replay attacks and ensure that transactions are processed in the correct order. Each account has a sequence number associated with it. When you sign and submit a transaction, you include the current sequence number of your account. The chain then checks this sequence number against the current sequence number of your account on chain. If they match, the transaction is processed; if not, you'll receive a mismatch error.

I have confirmed that the `wasm upload` processes is operational in CLI 0.3.8. I'm going to close this issue, and we can create a more current issue if this problem is encountered or reported again.

<img width="1012" alt="wasm upload on terra" src="https://github.com/andromedaprotocol/andromeda.js/assets/60895101/d93593b1-a8ed-48d9-942c-98ddd32db63a">

**Closed as completed by leifasorensen** 2024-02-14 14:57 UTC
Labels: bug
