### ISSUE TITLE
Getting errors on CLI when changing chain or wallet

### ISSUE THREAD

**Issue by MyronKoch-dev** [andromedaprotocol/andromeda.js#84] opened 2023-09-15 21:57 UTC
After updating CLI, when changing chains or wallets, I now get the following error

? AndromedaTest1@galileo-3> wallet use
? Select wallet to use: AndromedaTest1
- Connecting client...TypeError: signer.getAccounts is not a function
    at CosmClient.connect (/usr/local/lib/node_modules/@andromedaprotocol/cli/node_modules/@andromedaprotocol/andromeda.js/dist/clients/CosmClient.js:17:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AndromedaClient.connect (/usr/local/lib/node_modules/@andromedaprotocol/cli/node_modules/@andromedaprotocol/andromeda.js/dist/AndromedaClient.js:44:9)

![Screenshot 2023-09-15 at 4 00 34 PM](https://github.com/andromedaprotocol/andromeda.js/assets/137090178/b9b51bdc-c01c-43ca-90d3-e271b9d00b86)
![Screenshot 2023-09-15 at 4 00 04 PM](https://github.com/andromedaprotocol/andromeda.js/assets/137090178/25a5c623-73c6-443e-ab6f-b47e80695e1c)

**Comment by tulipesombre** [comment] 2023-10-08 09:16
I have the same issue and can't seem to find a way to solve it. I've tried reinstalling node.js etc. but still won't work. I believe there's an error in my package ... 

![image](https://github.com/andromedaprotocol/andromeda.js/assets/145696677/7f802277-ef72-4503-8ee2-ba85e66c3a43)

Have you found a way to solve this ?

**Comment by leifasorensen** [comment] 2024-01-30 23:31
This issue was resolved and has been confirmed to be working as intended in version 0.3.8.

![chain config loading](https://github.com/andromedaprotocol/andromeda.js/assets/60895101/c3f48ec3-370a-4235-be30-cc450bfc1cea)

Closing Issue as resolved.

**Closed as completed by leifasorensen** 2024-01-30 23:31 UTC
